### ISSUE TITLE
Replace w64devkit Docker build from the script

### ISSUE THREAD

**Issue by viferga** [metacall/distributable-windows#3]
I just have discovered that w64devkit is also distributed as binaries. So we do not need to build it ourselves, and we won't depend on docker to build it.

Here's the link of the distribution: https://github.com/skeeto/w64devkit/releases/download/v1.10.0/w64devkit-1.10.0.zip

We can used a fixed version from the releases: https://github.com/skeeto/w64devkit/releases/tag/v1.10.0

We should replace this:
https://github.com/metacall/distributable-windows/blob/f44df584c53cf0e6819b28ee741dd225f2923a5b/build.bat#L5-L10

By a script that directly downloads the w64devkit.

**Comment by sagarkumar3105** [comment]
Done.
